# Generated by Django 3.2.8 on 2023-11-26 02:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_portfolio_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
