# Generated by Django 3.2.8 on 2023-11-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20231126_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='body',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
